# Generated by Django 5.1.4 on 2024-12-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_estate_index',
            field=models.IntegerField(default=0),
        ),
    ]
