# Generated by Django 5.1.4 on 2024-12-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0006_remove_profile_current_estate_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='free_ads_remaining',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_shown_estate_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rent_types',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
