# Generated by Django 5.1.4 on 2024-12-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0009_profile_free_ads_remaining_profile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='estate_type',
            field=models.CharField(choices=[('квартира', 'Квартира'), ('будинок', 'Будинок'), ('кімната', 'Кімната'), ('інше', 'Інше')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate_bot.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='ru_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='uk_description',
            field=models.TextField(blank=True),
        ),
    ]
