# Generated by Django 5.1.4 on 2024-12-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0010_realestate_estate_type_realestate_is_for_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
