# Generated by Django 5.1.4 on 2024-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0011_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
