# Generated by Django 5.1.4 on 2024-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0012_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uk', 'Українська')], max_length=2),
        ),
    ]
