# Generated by Django 5.1.4 on 2024-12-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0014_remove_leasedraft_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasedraft',
            old_name='ru_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='ru_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='leasedraft',
            name='uk_description',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='uk_description',
        ),
    ]
