# Generated by Django 5.1.4 on 2024-12-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_bot', '0016_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('start', 'Start'), ('choose_language', 'Choose Language'), ('register_name', 'Register Name'), ('register_phone', 'Register Phone'), ('register_age', 'Register Age'), ('rent_choose_type', 'Choose Rent Type'), ('rent_choose_price', 'Choose Rent Price'), ('show_variants', 'Show Variants'), ('lease_photos', 'Upload Lease Photos'), ('lease_type', 'Choose Lease Type'), ('lease_type_custom', 'Custom Lease Type'), ('lease_price', 'Enter Lease Price'), ('lease_rooms', 'Enter Number of Rooms'), ('lease_description', 'Enter Description'), ('lease_confirm', 'Confirm Lease'), ('contact_moderator', 'Contact Moderator')], default='start', max_length=20),
        ),
    ]
